### ISSUE TITLE
Access to innovaphone via websockets without myApps

### ISSUE THREAD

**Issue by marcus-franzen** [innovaphone/websocketphp8#1]
@Elompenta 

Hi Sebastian,

is it possible to access the innovaphone platform via websockets without implementing a myApps-application?

Many thanks!
Marcus

**Comment by Elompenta** [comment]
Hi Marcus,

yes, at least you need an authentication to the PBX. 
You can reach this by an App Object in the PBX and make an authorization to this object.

We have an example here: https://sdk.innovaphone.com/13r3/doc/tutorials/ExternalAppService.htm

After authentication, you can use the functionalities / APIs, that are allowed in your app object.

For further questions, please use our developer forum: https://class.innovaphone.com/moodle2/mod/forum/view.php?id=127446
